### ISSUE TITLE
Contact us Page in the front end

### ISSUE THREAD

**Issue by Nicolej11** [Michaelc322/YUPP#17]

**Comment by jjxmes** [comment]
Closed by commit [71abff4]

**Comment by jjxmes** [comment]
Closed by commit 71abff4

**Comment by jjxmes** [comment]
Additionally worked on with commit [8a292ea](https://github.com/Michaelc322/YUPP/commit/8a292ea0301ac6b0ebb854e61c5c7572fcfd4353)
