### ISSUE TITLE
Displaying 2 restaurant sales - James 

### ISSUE THREAD

**Issue by Nicolej11** [Michaelc322/YUPP#28]
James' API endpoints for the backend logic of displaying restaurant sales.

**Comment by jjxmes** [comment]
Inputted Wingstop and steak n shake into the mongo db database

**Comment by jjxmes** [comment]
Code used for database:

{
        "_id": "674e60aa388accbff7f2c491",
        "restaurantName": "Steak 'n Shake",
        "cuisine": "Fast Food",
        "priceLevel": "$",
        "latitude": 30.463590414882532,
        "longitude": -84.36037815442616,
        "address": "1459 Capital Circle NW, Tallahassee, FL 32303",
        "activeDeals": [
            "(Four Meal Deals): Original Double Steakburger with Cheese and Fries $5.79",
            "Garlic Single Steakburger and Fries $5.79"
        ],
        "__v": 0
    },
    {
        "_id": "674e6117388accbff7f2c494",
        "restaurantName": "WingStop",
        "cuisine": "Fast Food",
        "priceLevel": "$$",
        "latitude": 30.452484255481885,
        "longitude": -84.31644201506667,
        "address": "1964 W Tennessee St #4, Tallahassee, FL 32304",
        "activeDeals": [
            "Boneless Meal Deal: Comes with 20 Boneless Wings in your choice of 4 flavors, with a large fry and 2 dips."
        ],
        "__v": 0
    },
