### ISSUE TITLE
Displaying 2 restaurant sales - Tyler

### ISSUE THREAD

**Issue by Nicolej11** [Michaelc322/YUPP#29]
Tyler's API endpoints for the backend logic of displaying restaurant sales.

**Comment by tylercarver16** [comment]
Added Chick fil a and Chipotle to database

**Comment by tylercarver16** [comment]
{
    "restaurantName": "Chick-fil-a",
    "cuisine": "Fast Food",
    "priceLevel": "$",
    "latitude": 30.448831930223236,
    "longitude": -84.31044767271823,
    "address": "1775 W Tennessee St, Tallahassee, FL 32304",
    "activeDeals": [
        "First 100 students at FSU baseball game get a free chicken sandwich"
    ],
    "_id": "675091a5cd024014377297a3",
    "__v": 0
}

**Comment by tylercarver16** [comment]
{
    "restaurantName": "Chipotle",
    "cuisine": "Fast Food",
    "priceLevel": "$",
    "latitude": 30.448813117454502,
    "longitude": -84.31108598018145,
    "address": "1801 W Tennessee St, Tallahassee, FL 32304",
    "activeDeals": [
        "BOGO coupon code: ENBF84z"
    ],
    "_id": "6750917dcd024014377297a0",
    "__v": 0
}
