### ISSUE TITLE
Displaying 2 restaurant sales - Tanner 

### ISSUE THREAD

**Issue by Nicolej11** [Michaelc322/YUPP#30]
Tanners API endpoints for the backend logic of displaying restaurant sales.

**Comment by TannerR20** [comment]
added restaurants to the database.


restaurantName: Taco Bell,
cuisine: Mexican,
priceLevel: $,
latitude: 30.44998744658135,
longitude:  -84.30715602618538,
address: 1506 W Tennessee St, Tallahassee, FL 32304,
activeDeals: 10 Craving value items for $3 or less, Luxe Cravings Box ft 90s Gordita Supreme for $8.99 

restaurantName: Wendy's,
cuisine: American,
priceLevel: $,
latitude: 30.44171355816235,
longitude:  -84.33776816221508,
address: 3030 W Pensacola St, Tallahassee, FL 32304,
activeDeals: $3.99 for spicy chicken sandwich in app, $5 biggie bag
